In [1]:
import pandas as pd 
import numpy as np

In [2]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import FunctionTransformer

In [3]:
matrix= np.array([[7, 16, 31], [np.nan, np.nan, 66], [12, 5, np.nan],[98, np.nan, 92]])

In [4]:
matrix.shape

(4, 3)

In [5]:
matrix

array([[ 7., 16., 31.],
       [nan, nan, 66.],
       [12.,  5., nan],
       [98., nan, 92.]])

In [6]:
c=SimpleImputer(strategy='mean').fit_transform(matrix)

In [7]:
c

array([[ 7. , 16. , 31. ],
       [39. , 10.5, 66. ],
       [12. ,  5. , 63. ],
       [98. , 10.5, 92. ]])

In [8]:
matrix=np.array([[1, 1], [2, 3],[10,100]])

In [9]:
matrix

array([[  1,   1],
       [  2,   3],
       [ 10, 100]])

In [10]:
c=FunctionTransformer(func=np.log10).fit_transform(matrix)

In [11]:
c

array([[0.        , 0.        ],
       [0.30103   , 0.47712125],
       [1.        , 2.        ]])